server:
  port: 8040
  servlet:
    context-path: /
spring:
  profiles:
    active: dev
# actuator
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        #显示所有端点
        include: "*"
